<?php
/**
 * @file
 * A block module that displays DTN News Feeds.
 */

 include_once('dtn_includes.inc');
?>
<?php
function dtn_news_block_info() {
  $blocks = array();
  $blocks['dtn_news'] = array(
    'info' => t('DTN News Block'),
    'status' => 1,
  );
  return $blocks;
}

function  dtn_news_block_view($delta='dtn_news') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
	case 'dtn_news':
      $block['subject'] = t('DTN News');
      $block['content'] = get_dtn_news_html();
      break;
    }
  return $block;
}

function dtn_news_menu() {
	$items = array ();
	$items['admin/config/DTN'] = array(
	  'title' => 'DTN News Feeds',
	  'description' => 'Configuration for the DTN News Module',
	  'page callback' => 'drupal_get_form',
	  'page arguments' => array('array_dtn_news_form'),
	  'access arguments' => array('administer users'),
	  'type' => MENU_NORMAL_ITEM,
	);

}

function dtn_news_form($form, &$form_state){
	$form['dtn_url'] = array(
	  '#type' => 'textfield',
	  '#default_value' => variable_get('dtn_url','http://agquote.dtn.com/news/processdtnagnewstagv3.cfm'),
	  '#title' => t('DTN News URL'),
	  '#description' => t('The URL of the DTN News Module that we will perform callbacks against'),
	  '#size' => 80,
	  '#maxlength' => 120,
	  '#required' => TRUE,
	);
	$form['dtn_username'] = array(
	  '#type' => 'textfield',
	  '#default_value' => variable_get('dtn_username','Your Username'),
	  '#title' => t('DTN Username'),
	  '#description' => t('The Username for the DTN News Module '),
	  '#size' => 20,
	  '#maxlength' => 60,
	  '#required' => TRUE,
	);
	$form['dtn_password'] = array(
	  '#type' => 'textfield',
      '#default_value' => variable_get('dtn_password','Your Password'),
	  '#title' => t('DTN Password'),
	  '#description' => t('The Password for the DTN News Module '),
	  '#size' => 20,
	  '#maxlength' => 60,
	  '#required' => TRUE,
	);
	$form['dtn_service'] = array(
	  '#type' => 'select',
	  '#title' => t('DTN Service'),
      '#options' => array(
        0 => t('NEWS'),
        1 => t('WEATHER'),
        2 => t('HEADNEWS'),
        2 => t('MKTNEWS'),
       ),
      '#default_value' => $category['dtn_service'],
      '#description' => t('Set the correct value for the service you wish displayed.'),
	);
	$form['submit'] = array(
	  '#type' => 'submit',
	  '#value' => t('Save Configuration'),
	);
	return $system_settings_form($form);
}

function get_values($url) {
//setup the array of values,drupal likes arrays.
	$news_string = array (
	  'url'		 => variable_get('dtn_url'),
             'username' => variable_get('dtn_user'),
	  'password' => variable_get('dtn_password'),
	  'service'  => variable_get('dtn_service'),
	  'storyid'  =>	NULL,
	  'XML'	     => 'XML',
	);
	//call function in includes to take array and return urlencoded url
	$url=createDTNURL($news_string);
	return $url;

}

function get_dtn_news_html () {
  $url=get_values() ;
  $ch = curl_init($url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  $c = curl_exec($ch);
  curl_close($ch);
  $c = xml2array($c);

drupal_set_message('&lt;pre&gt;' . print_r($c, TRUE) . '&lt;/pre&gt;');
}
